"""esquema inicial grupo 1 - organizacion

Revision ID: 4b57a766e067
Revises: 
Create Date: 2026-09-17 13:31:11.367588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4b57a766e067'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciclo_ebr',
    sa.Column('id_ciclo', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_ciclo')
    )
    op.create_table('colegio',
    sa.Column('id_colegio', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zona', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id_colegio')
    )
    op.create_table('docente',
    sa.Column('id_docente', sa.Integer(), nullable=False),
    sa.Column('nombres', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apellidos', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_docente')
    )
    op.create_table('periodo_academico',
    sa.Column('id_periodo', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_periodo')
    )
    op.create_table('programa',
    sa.Column('id_programa', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_programa')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('grado',
    sa.Column('id_grado', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_ciclo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ciclo'], ['ciclo_ebr.id_ciclo'], ),
    sa.PrimaryKeyConstraint('id_grado')
    )
    op.create_table('periodo_evaluacion',
    sa.Column('id_periodo_evaluacion', sa.Integer(), nullable=False),
    sa.Column('id_periodo', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_periodo'], ['periodo_academico.id_periodo'], ),
    sa.PrimaryKeyConstraint('id_periodo_evaluacion')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('correo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_docente', sa.Integer(), nullable=True),
    sa.Column('nombres', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apellidos', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_docente'], ['docente.id_docente'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_table('alumno',
    sa.Column('id_alumno', sa.Integer(), nullable=False),
    sa.Column('nombres', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apellidos', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_colegio', sa.Integer(), nullable=False),
    sa.Column('id_grado', sa.Integer(), nullable=False),
    sa.Column('id_programa_actual', sa.Integer(), nullable=False),
    sa.Column('classroom_razkids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_colegio'], ['colegio.id_colegio'], ),
    sa.ForeignKeyConstraint(['id_grado'], ['grado.id_grado'], ),
    sa.ForeignKeyConstraint(['id_programa_actual'], ['programa.id_programa'], ),
    sa.PrimaryKeyConstraint('id_alumno')
    )
    op.create_table('docente_colegio_grado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_docente', sa.Integer(), nullable=False),
    sa.Column('id_colegio', sa.Integer(), nullable=False),
    sa.Column('id_grado', sa.Integer(), nullable=False),
    sa.Column('id_periodo_evaluacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_colegio'], ['colegio.id_colegio'], ),
    sa.ForeignKeyConstraint(['id_docente'], ['docente.id_docente'], ),
    sa.ForeignKeyConstraint(['id_grado'], ['grado.id_grado'], ),
    sa.ForeignKeyConstraint(['id_periodo_evaluacion'], ['periodo_evaluacion.id_periodo_evaluacion'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumno_programa_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_alumno', sa.Integer(), nullable=False),
    sa.Column('id_programa', sa.Integer(), nullable=False),
    sa.Column('id_periodo_evaluacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumno.id_alumno'], ),
    sa.ForeignKeyConstraint(['id_periodo_evaluacion'], ['periodo_evaluacion.id_periodo_evaluacion'], ),
    sa.ForeignKeyConstraint(['id_programa'], ['programa.id_programa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alumno_programa_historial')
    op.drop_table('docente_colegio_grado')
    op.drop_table('alumno')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('periodo_evaluacion')
    op.drop_table('grado')
    op.drop_table('rol')
    op.drop_table('programa')
    op.drop_table('periodo_academico')
    op.drop_table('docente')
    op.drop_table('colegio')
    op.drop_table('ciclo_ebr')
    # ### end Alembic commands ###
